---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "§l§a•SkyBlock §cCre§eSix§bVN2019"
OutdatedClient:
  custom: true
  message: "§l§cchỉnh lại phiên bản đi nhé!"
OutdatedServer:
  custom: true
  message: "&cOops! Server outdated!"
WhitelistedServer:
  custom: true
  message: "&c&oThis Server is whitelisted!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, The Server is full&c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "&2[{TIME}] &a{PLAYER}&d lần đầu tiên vào server >_<"
Join:
  hide: false
  custom: true
  message: "§l§e{PLAYER} đã vào sv ^_^"
Quit:
  hide: true
  custom: false
  message: "§l§c{PLAYER}&e thoát game rồi bà con @@"
WorldChange:
  enable: true
  message: "&2[{TIME}] &a{PLAYER}&e moved from &c{ORIGIN}&e to &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "&c{PLAYER} chết r"
  death-contact-message:
    hide: false
    custom: true
    message: "&l§e {PLAYER} Bị giết bởi {BLOCK}"
  kill-message:
    hide: false
    custom: true
    message: "§l&9{PLAYER} &e Đã bị giết bởi&c{KILLER}"
  death-projectile-message:
    hide: false
    custom: true
    message: "&c{PLAYER} đã bị {KILLER} by arrow"
  death-suffocation-message:
    hide: false
    custom: true
    message: "&c{PLAYER} nghẹt thở"
  death-fall-message:
    hide: false
    custom: true
    message: "&c{PLAYER} mô phật rơi từ nơi cao xuống"
  death-fire-message:
    hide: false
    custom: true
    message: "&c{PLAYER} đi lên trong ngọn lửa"
  death-on-fire-message:
    hide: false
    custom: true
    message: "§l&c{PLAYER} bị bỏng :v"
  death-lava-message:
    hide: false
    custom: true
    message: "&c{PLAYER} cố gắng bơi trong dung nham"
  death-drowning-message:
    hide: false
    custom: true
    message: "&c{PLAYER} chết đuối"
  death-explosion-message:
    hide: false
    custom: true
    message: "&c{PLAYER} phát nổ"
  death-void-message:
    hide: false
    custom: true
    message: "&c{PLAYER} rơi vào khoảng trống"
  death-suicide-message:
    hide: false
    custom: true
    message: "§l&e{PLAYER} tự sát"
  death-magic-message:
    hide: false
    custom: true
    message: "§l&c{PLAYER} đã bị giết bởi một lời nguyền :v"
...