#   _______                       __        __    __
#  /       \                     /  |      /  |  /  |
#  $$$$$$$  |  ______   _______  $$ |   __ $$ |  $$ |  ______
#  $$ |__$$ | /      \ /       \ $$ |  /  |$$ |  $$ | /      \
#  $$    $$<  $$$$$$  |$$$$$$$  |$$ |_/$$/ $$ |  $$ |/$$$$$$  |
#  $$$$$$$  | /    $$ |$$ |  $$ |$$   $$<  $$ |  $$ |$$ |  $$ |
#  $$ |  $$ |/$$$$$$$ |$$ |  $$ |$$$$$$  \ $$ \__$$ |$$ |__$$ |
#  $$ |  $$ |$$    $$ |$$ |  $$ |$$ | $$  |$$    $$/ $$    $$/
#  $$/   $$/  $$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/  $$$$$$$/
#                                                    $$ |
#  The easy prison rankup plugin for PocketMine-MP   $$ |
#                                                    $$/

unleash-the-rankupdoesgroups: true
  # If you set this to false RankUpDoesGroups won't be loaded.
  # This means that you can't set it as your groupmanager.
  # It is highly recommended not to change this
preferred-economy: false
  # Set your preferred economy
  # rankup\\economy\\Economy and rankup\\economy\\PocketMoney are available by default
  # Set to false for autoloading (only officially supported economys will autoload).
preferred-groupmanager: "rankup\\permission\\RankUpDoesGroups"
  # Set your preferred group manager
  # rankup\\permission\\RankUpDoesGroups and rankup\\permission\\PurePerms are available.
  # RankUpDoesGroups is a super barebones alternative for users who don't use PurePerms

ranks: # Define all your ranks here
  B: 20000
  C: 50000
  D: 200000
  E: 400000
  F: 650000
  G: 1000000
  H: 1500000
  I: 2000000
  J: 2500000
  K: 3000000
  M: 3500000
  "N": 4000000
  O: 5000000
  P: 6000000
  Q: 8000000
  S: 10000000
  T: 15000000
  U: 20000000
  V: 25000000
  W: 30000000
  "Y": 50000000
  Z: 60000000
  

lang:
  ranked-up-paid: "§l§a•Rank Của Bạn Đã Được Nâng Lên Bậc %s"
  ranked-up-free: "§l§a•Rank Của Bạn Đã Được Nâng Lên Bậc %s"
  group-add-error-paid: "Không Thể Nâng Cấp Bậc Của Bạn.Tiền Đã được Hoàn Lại"
  group-add-error-free: "Không Thể Nâng Cấp Bậc Của Bạn.Xin Thử Lại."
  need-more-money-1: "Đáng Tiếc Bạn Không Có Đủ Tiền Để Nâng Cấp."
  need-more-money-2: "§l§cBạn Cần %s Để Nâng Cấp Rank :Cố cố lên nào"
  missing-economy: "Không Đủ Kinh Tế."
  have-max-rank: "§eĐã Đạt Giới Hạn Cấp Bậc."
  command-permission-error: "§dYou don't have permission to rankup."


